### ISSUE TITLE
Support auxilliaries in Universe definitions

### ISSUE THREAD

**Issue by dotsdl** [datreant/MDSynthesis#59]
Universes can now [iterate through auxiliary data](https://github.com/MDAnalysis/mdanalysis/issues/785) in addition to a trajectory. We want to [persist defined auxiliaries](https://github.com/MDAnalysis/mdanalysis/issues/843#issuecomment-233412691) in the Universe definition for a Sim in the same way that we persist other information, such as kwargs.

**Comment by jbarnoud** [comment]
@fiona-naughton implemented a `AuxReader.get_description` method that can be used for this purpose. It returns a dictionary that can be passed to `Reader.add_auxiliary` to regenerate the auxiliary reader.

**Comment by dotsdl** [comment]
@jbarnoud perfect. Once mdanalysis/mdanalysis#868 is merged I'll be happy to get this in. I don't think the implementation will be hard or weird.

**Comment by dotsdl** [comment]
Closing for now. Can re-open later if there's renewed interest in this functionality.
