### ISSUE TITLE
Remove Sim treanttype

### ISSUE THREAD

**Issue by dotsdl** [datreant/MDSynthesis#65]
In the spirit of datreant/datreant.core#100, we want to get rid of the concept of ``treanttype``s and make all statefiles have names like ``Treant.<uuid>.json``. This has the benefit that tools such as [datreant.cli](https://github.com/datreant/datreant.cli) can easily work with **all** Treants, not just those generated with ``datreant.core``. It also greatly simplifies the relationship between ``datreant`` and libraries such as ``mdsynthesis``, allowing us to fix some annoying behavior.

To accomplish this consistently, ``mdsynthesis`` must at least:

1. Feature its own ``discover`` method that **only** selects ``Treant``s that already feature the ``mdsynthesis`` namespace in their state file, returning these as ``Sim`` objects. This will come with a performance penalty since now the files must be parsed to check for this condition, whereas before the filename encoded this.
2. Have a ``Sim`` object that, upon use on an existing ``Treant`` file, creates the ``mdsynthesis`` namespace marking it as a ``Sim`` for later discovery.
3. Not change the behavior of any ``datreant`` components on import, such as ``discover`` or ``Bundle``, as it currently does.

In order for this scheme to work consistently, ``datreant.core.Bundle`` must be modified to not allow paths as input, but instead only take ``Treant`` objects or their subclasses directly (otherwise it's not clear what class to use on the path). Must check that serialization and deserialization still works under this scheme.

**Comment by kain88-de** [comment]
> In order for this scheme to work consistently, datreant.core.Bundle must be modified to not allow paths as input, but instead only take Treant objects

That sounds like a sane idea. Makes the code more explicit anyway.

**Comment by dotsdl** [comment]
This is being addressed in #70. Almost there. :grin:

**Comment by dotsdl** [comment]
With #70 merged, closing.
