### ISSUE TITLE
Order of Treants in a Bundle

### ISSUE THREAD

**Issue by sperezconesa** [datreant/MDSynthesis#83]
Hello,

I would like to know if there is some way to order the treants inside a bundle for example on the basis of category. I want this because if I do something like:
```python
list_variables= [universe_of_treant_0, universe_of_treant_1, universe_of_treant_2]
for variable,treant in zip(list_of_variables, bundle):
    assign universe of treant to variable
```
And therefore if I don't have control over the order in which the treants are iterated over I might missasign the variables.
Thank you very!
Sergio

**Comment by dotsdl** [comment]
Hi @sperezconesa!

If you have a category giving your desired order when sorted, you could use `numpy.argsort` to get back the indices of the values in sorted order, then use those indices to produce a new Bundle with that sort scheme.

For example, using `datreant`:

```python

>>> import datreant as dtr
>>> import numpy as np

# ghosts in PacMan
>>> for i in ('inky', 'blinky', 'pinky', 'clyde'):
        dtr.Treant(i)

>>> b = dtr.discover()
>>> b
<Bundle(['pinky', 'inky', 'clyde', 'blinky'])>

# set the ghosts' color as a category; we set in the order they
# happen to be in *this* Bundle
>>> b.categories['color'] = ['pink', 'cyan', 'orange', 'red']

# np.argsort will give back an array giving the index of our category 
# 'color' that should be in each array position in order to be sorted
>>> np.argsort(b.categories['color'])
array([1, 2, 0, 3])

# we can use that as a fancy index to get a new Bundle, 
# sorted according to the category
>>> b[np.argsort(b.categories['color'])]
<Bundle(['inky', 'clyde', 'pinky', 'blinky'])>

# sanity check: these should be alphanumerically sorted
>>> b[np.argsort(b.categories['color'])].categories
<AggCategories({'color': ['cyan', 'orange', 'pink', 'red']})>
```

**Comment by sperezconesa** [comment]
ah! Of course, I didn't think of using regular numpy. Thanks a lot!
By the way I love this library. Now it's in all my workflows.

**Comment by dotsdl** [comment]
Awesome, I'm happy to hear! It's a fun little library; I'm likely getting back into using it more frequently myself very soon. :grin:
